Website = "https://github.com/sebastianrau/focusrite-mackie-control/"

[Details]
Icon = "logo.png"
Name = "Monitor Controller"
ID = "com.github.sebastianrau.focusrite-mackie-control"
Version = "0.1.3"
Build = 1